### ISSUE TITLE
Fix Openlane CI

### ISSUE THREAD

**Issue by secworks** [secworks/prince#4]
Openlane action dies:

´´´
[INFO]: Using design configuration at /project/sky130-openlane/config.tcl
[INFO]: Sourcing Configurations from /project/sky130-openlane/config.tcl
[INFO]: PDKs root directory: /home/runner/work/prince/prince/pdklite
[INFO]: PDK: sky130A
[INFO]: Setting PDKPATH to /home/runner/work/prince/prince/pdklite/sky130A
[INFO]: Standard Cell Library: sky130_fd_sc_hd
no such variable
    (read trace on "::env(STD_CELL_LIBRARY_OPT)")
    invoked from within
"set ::env(TECH_LEF_OPT) "$::env(PDK_ROOT)/$::env(PDK)/libs.ref/$::env(STD_CELL_LIBRARY_OPT)/techlef/$::env(STD_CELL_LIBRARY_OPT).tlef""
    (file "/home/runner/work/prince/prince/pdklite/sky130A/libs.tech/openlane/config.tcl" line 31)
    invoked from within
"source $pdk_config"
    (procedure "prep" line 129)
    invoked from within
"prep {*}$args"
    (procedure "run_non_interactive_mode" line 12)
    invoked from within
"run_non_interactive_mode {*}$argv"
    invoked from within
"if { [info exists flags_map(-interactive)] || [info exists flags_map(-it)] } {
	puts_info "Running interactively"
	if { [info exists arg_values(-file)..."
    (file "/openLANE_flow/flow.tcl" line 223)
make: *** [Makefile:4: all] Error 1
ERROR: Failed to build secworks:crypto:prince:0 : '['make']' exited with an error: 2
```
@olofk Any idea?

**Comment by olofk** [comment]
Just found this bug report. Hopefully fixed now
